align top bar
aegisbigdata/hopsworks pull request #23
Opened 2019-03-28 10:25 UTC by Ambradibi

File pages
 - top bar alignment
 - box alignment

2019-04-02 02:54 UTC, cbotsikas requested changes

2019-04-02 02:54 UTC, cbotsikas commented on aegis-web/yo/app/styles/filebrowser.css
> +  height: 100%;
This property is breaking the bottom shadow of the files box. I don't know why you added it so i can judge if you need to keep it or not but somehow the shadow should be fixed.
![image](https://user-images.githubusercontent.com/1640100/55372447-13ae5b00-5502-11e9-906c-9b53796d5ca7.png)

2019-04-02 02:54 UTC, cbotsikas commented on aegis-web/yo/app/styles/filebrowser.css
> +  height: 50%;
This is also affecting AEGIS tools (maybe other places too). Why do you need to set the height like that?
![image](https://user-images.githubusercontent.com/1640100/55372816-4a38a580-5503-11e9-8280-70c5f9ba2a8e.png)

2019-04-02 07:53 UTC, Ambradibi commented
![image (1)](https://user-images.githubusercontent.com/47423916/55385203-e9be5e00-552c-11e9-8781-17da622c5a9d.png)

To fix this. If it breaks on another page I create a new custom class, but to fix the boxes I have to set a height. Do you have another solution?

2019-04-09 08:13 UTC, cbotsikas approved these changes

2019-04-09 08:14 UTC, merged