Extend metadata creation pages (Project/Dataset/Distribution)
aegisbigdata/hopsworks pull request #36
Opened 2019-05-03 14:57 UTC by Kritzzz

See Issue [aegisbigdata/documentation#131](https://github.com/aegisbigdata/documentation/issues/131).

2019-05-03 15:07 UTC, cbotsikas requested changes
See inline comments

2019-05-03 15:07 UTC, cbotsikas commented on aegis-web/yo/app/index.html
> -    <link rel="stylesheet" href="bower_components/css-hamburgers/dist/hamburgers.css" />
Why is this removed? Please check all references.

2019-05-03 15:07 UTC, cbotsikas commented on aegis-web/yo/bower.json
> -    "css-hamburgers": "^1.1.3"
Same here

2019-05-03 15:12 UTC, cbotsikas commented
I think this is a common issue, seen in other PRs too. I haven't looked for the reason but some references are automatically changed at some point. for example on older PR #31 see[ the revert commit](https://github.com/aegisbigdata/hopsworks/pull/31/commits/790e738b623a29481ad3bbb590f7ac6c244639d7)

Please check what changed you need in index.html and revert the rest. Same for bower.json

2019-05-03 15:16 UTC, cbotsikas commented on aegis-web/yo/bower.json
> -    "css-hamburgers": "^1.1.3"
ah, this one is ok. I didn't notice the reference below.

2019-05-03 15:17 UTC, cbotsikas commented
bower.json is fine. Just check index.html

2019-05-06 07:20 UTC, fabiankirstein approved these changes

2019-05-06 07:20 UTC, FabiApfelkern commented
@cbotsikas I fixed it. I think those includes are generated by Grunt. So it actually includes what it needs... We should ask KTH.

2019-05-06 07:23 UTC, cbotsikas approved these changes

2019-05-06 07:23 UTC, merged